### ISSUE TITLE
BUG - Unable to update ProTA to version tavmod-4.4 when ProTA 4.4 is already installed

### ISSUE THREAD

**Issue by ageekhere** [ta-forever/downlords-taf-client#13]
**Describe the bug**
When auto update feature is enabled and ProTA 4.4 is already installed the client will give an error

**To Reproduce**
enable auto update feature while having ProTA 4.4 installed and host a game.

**Log or error message**
`
unable to update ProTA to version tavmod-4.4

java.util.concurrent.CompletionException: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of reset command. org.eclipse.jgit.api.errors.FilterFailedException: Execution of filter command 'git-lfs smudge -- 'TotalA.exe'' on file 'TotalA.exe' failed with return code '1', message on stderr: ''git-lfs' is not recognized as an internal or external command,
operable program or batch file.
'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1194)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at com.faforever.client.patch.GitLfsFeaturedModUpdater.updateMod(GitLfsFeaturedModUpdater.java:140)
	at com.faforever.client.patch.GameUpdaterImpl.updateFeaturedMod(GameUpdaterImpl.java:76)
	at com.faforever.client.patch.GameUpdaterImpl.update(GameUpdaterImpl.java:40)
	at com.faforever.client.game.GameService.updateGameIfNecessary(GameService.java:819)
	at com.faforever.client.game.GameService.lambda$runWithReplay$36(GameService.java:587)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of reset command. org.eclipse.jgit.api.errors.FilterFailedException: Execution of filter command 'git-lfs smudge -- 'TotalA.exe'' on file 'TotalA.exe' failed with return code '1', message on stderr: ''git-lfs' is not recognized as an internal or external command,
operable program or batch file.
'
	at org.eclipse.jgit.api.ResetCommand.call(ResetCommand.java:209)
	at com.faforever.client.patch.GitLfsFeaturedModUpdater.resetExceptUserIniFiles(GitLfsFeaturedModUpdater.java:197)
	at com.faforever.client.patch.GitLfsFeaturedModUpdater.doUpdate(GitLfsFeaturedModUpdater.java:233)
	at com.faforever.client.patch.GitLfsFeaturedModUpdater.lambda$updateMod$3(GitLfsFeaturedModUpdater.java:153)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	... 12 more
Caused by: java.io.IOException: org.eclipse.jgit.api.errors.FilterFailedException: Execution of filter command 'git-lfs smudge -- 'TotalA.exe'' on file 'TotalA.exe' failed with return code '1', message on stderr: ''git-lfs' is not recognized as an internal or external command,
operable program or batch file.
'
	at org.eclipse.jgit.dircache.DirCacheCheckout.runExternalFilterCommand(DirCacheCheckout.java:1718)
	at org.eclipse.jgit.dircache.DirCacheCheckout.getContent(DirCacheCheckout.java:1679)
	at org.eclipse.jgit.dircache.DirCacheCheckout.getContent(DirCacheCheckout.java:1609)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkoutEntry(DirCacheCheckout.java:1535)
	at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:569)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:471)
	at org.eclipse.jgit.api.ResetCommand.checkoutIndex(ResetCommand.java:414)
	at org.eclipse.jgit.api.ResetCommand.call(ResetCommand.java:182)
	... 16 more
Caused by: org.eclipse.jgit.api.errors.FilterFailedException: Execution of filter command 'git-lfs smudge -- 'TotalA.exe'' on file 'TotalA.exe' failed with return code '1', message on stderr: ''git-lfs' is not recognized as an internal or external command,
operable program or batch file.
'
	at org.eclipse.jgit.dircache.DirCacheCheckout.runExternalFilterCommand(DirCacheCheckout.java:1721)
	... 23 more

`

**Expected behavior**
The client should check for updates and installs them 

**OS**
Windows

**Comment by ageekhere** [comment]
Update
deleting .git file fixes the issue
somehow the .git folder got corrupted, maybe by watching replays/live games or something else.
