### ISSUE TITLE
Linux Java 17 not supported, how get 18?

### ISSUE THREAD

**Issue by Pithikos** [ta-forever/downlords-taf-client#70]
I'm trying to install on Ubuntu 20.04. Really unfortunate that Java was used for this client because it makes it a pain in the ass to install.

When running `./taf-java-client` it shows
```
No suitable Java Virtual Machine could be found on your system.
The version of the JVM must be at least 16 and at most 20.
Please define INSTALL4J_JAVA_HOME to point to a suitable JVM.
```

However it doesn't work with `openjdk-17-jre` and neither with `openjdk-21-jre` (which is the [only possible JRE I can find](https://www.oracle.com/java/technologies/downloads/)).

![image](https://github.com/ta-forever/downlords-taf-client/assets/400048/01409a65-e166-4e5c-b1a2-7e62b661f2d6)

In text
```
java.lang.UnsupportedClassVersionError: com/faforever/client/Main has been compiled by a more recent version of the Java Runtime (class file version 62.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:80)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:71)
	at install4j.com.faforever.client.Main.main(Unknown Source)
```

Any solution on how to get this working on Ubuntu 20.04?

**Comment by Pithikos** [comment]
Install JDK 18 on Ubuntu 20.04:
```
sudo apt install qtbase5-dev zlib1g git git-lfs wine winetricks
wget https://download.oracle.com/java/18/archive/jdk-18.0.2.1_linux-x64_bin.deb
sudo dpkg -i jdk-18.0.2.1_linux-x64_bin.deb
```
